@extends('master.admin')
@section('admin-title','Trades')
@section('admin-content')

    <div class="row">
        <div class="col">
            Displaying information for trade <span class="text-warning">{{$trade->id}}</span>
            <hr>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">

            <form action="{{route('admin.trade.update',$trade)}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="id">ID:</label>
                    <input type="text" name="id" id="id" class="form-control" value="{{$trade->id}}" readonly>
                </div>
                <div class="form-group">
                    <label for="base_coin">Base Coin:</label>
                    <input type="text" name="base_coin" id="base_coin" class="form-control" value="{{strtoupper($trade->base_coin)}}" readonly>
                </div>
                <div class="form-group">
                    <label for="other_coin">Other Coin:</label>
                    <input type="text" name="other_coin" id="other_coin" class="form-control" value="{{strtoupper($trade->other_coin)}}" readonly>
                </div>
                <div class="form-group">
                    <label for="required_payment">Required payment:</label>
                    <input type="text" name="required_payment" id="required_payment" class="form-control" value="{{$trade->required_payment}}" readonly>
                </div>
                <div class="form-group">
                    <label for="rate">Rate:</label>
                    <input type="text" name="rate" id="rate" class="form-control" value="{{$trade->rate}}" readonly>
                </div>
                <div class="form-group">
                    <label for="actual_rate">Actual rate:</label>
                    <input type="text" name="actual_rate" id="actual_rate" class="form-control" value="{{$trade->actual_rate}}" readonly>
                </div>
                <div class="form-group">
                    <label for="received_balance">Received balance:</label>
                    <input type="text" name="received_balance" id="received_balance" class="form-control" value="{{$trade->received_balance}}" readonly>
                </div>
                <div class="form-group">
                    <label for="expected_return">Expected return:</label>
                    <input type="text" name="expected_return" id="expected_return" class="form-control" value="{{$trade->expected_return}}" readonly>
                </div>
                <div class="form-group">
                    <label for="service_fee">Service Fee:</label>
                    <input type="text" name="service_fee" id="service_fee" class="form-control" value="{{$trade->service_fee}}" readonly>
                </div>
                <div class="form-group">
                    <label for="tx_fee">TX Fee:</label>
                    <input type="text" name="tx_fee" id="tx_fee" class="form-control" value="{{$trade->tx_fee}}" readonly>
                </div>
                <div class="form-group">
                    <label for="sent_amount">Sent amount: (Forward to exchange)</label>
                    <input type="text" name="sent_amount" id="sent_amount" class="form-control" value="{{$trade->sent_amount}}" readonly>
                </div>
                <div class="form-group">
                    <label for="forward_txid">Forward TXID:</label>
                    <input type="text" name="forward_txid" id="forward_txid" class="form-control" value="{{$trade->forward_txid}}" readonly>
                </div>
                <hr>
                <div class="form-group">
                    <p>
                        Editable
                    </p>
                </div>
                <div class="form-group">
                    <div class="form-group">
                        <label for="deposit_address">Deposit address: (Generated by service)</label>
                        <input type="text" name="deposit_address" id="tx_fee" class="form-control" value="{{$trade->deposit_address}}" >
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-group">
                        <label for="refund_address">Refund address: (Provided by user)</label>
                        <input type="text" name="refund_address" id="tx_fee" class="form-control" value="{{$trade->refund_address}}" >
                    </div>
                </div>
                <div class="form-group">
                    <label for="state">State:</label>
                    <select name="state" id="state" class="form-control">
                        @foreach(\App\Trade::getAvailableStates() as $state)
                            <option value="{{$state}}" @if($state == $trade->state) selected @endif>{{$state}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-warning">Edit trade</button>
                </div>
            </form>

            @include('admin.morphtrade',$trade)
        </div>
    </div>

@stop
